In [30]:
import pandas as pd
import plotly.express as px
import plotly.io as pio
pio.renderers.default = 'notebook' # force plotly to render inside the notebook

NYC People in Homless shelters + Evictions
1. How are eviction trends related to homelessness in New York City?
2. Do increases in evictions correspond with increases in the number of people staying in NYC homeless shelters?
3. Which boroughs experience the highest levels of eviction and homelessness.

In [35]:
df_evictions = pd.read_csv("Evictions_20260715.csv")
df_shelter_people = pd.read_csv("DHS_Daily_Report_20260715.csv")

In [36]:
df_evictions

,Court Index Number,Docket Number,Eviction Address,Eviction Apartment Number,Executed Date,Marshal First Name,Marshal Last Name,Residential/Commercial,BOROUGH,Eviction Postcode,Ejectment,Eviction/Legal Possession,Latitude,Longitude,Community Board,Council District,Census Tract,BIN,BBL,NTA
0,325688/23,26140,2565 MARION AVENUE APT 2C,2C,09/17/2025,Robert,Renzulli,Residential,BRONX,10458,Not an Ejectment,Possession,40.862931,-73.892217,7.0,15.0,39901.0,2016602.0,2.032860e+09,Bedford Park-Fordham North
1,57364/16*,166775,2776 JEROME AVENUE,1E,03/16/2017,Alfred,Locascio,Residential,BRONX,10468,Not an Ejectment,Possession,40.869722,-73.895327,7.0,14.0,40303.0,2017499.0,2.033180e+09,Van Cortlandt Village
2,330886/22A,123564,1563 METROPOLITAN AVENUE,4A,08/13/2025,Darlene,Barone,Residential,BRONX,10462,Not an Ejectment,Possession,40.839696,-73.858059,9.0,18.0,21001.0,2096772.0,2.039448e+09,Parkchester
3,318146/24B,144754,637 EAST 224TH STR EET,4F,09/11/2025,Justin,Grossman,Residential,BRONX,10466,Not an Ejectment,Possession,40.887742,-73.862843,12.0,12.0,394.0,2121925.0,2.048260e+09,Williamsbridge-Olinville
4,B304354/25,139836,445 GERARD AVENUE,W818,01/21/2026,Darlene,Barone,Residential,BRONX,10451,Not an Ejectment,Possession,40.817398,-73.929872,1.0,8.0,63.0,2001095.0,2.023510e+09,West Concourse
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130236,63313/18,61548,432 MILFORD STREET,2,06/04/2018,Howard,Schain,Residential,BROOKLYN,11208,Not an Ejectment,Possession,40.668334,-73.875262,5.0,42.0,1118.0,3393717.0,3.044560e+09,East New York
130237,76186/16A,65622,162 WEST 141ST ST,1,03/08/2018,Justin,Grossman,Residential,MANHATTAN,10030,Not an Ejectment,Possession,40.818617,-73.939809,10.0,9.0,230.0,1060077.0,1.020090e+09,Central Harlem North-Polo Grounds
130238,304096/23,16376,730 ROCKAWAY AVENUE APT 5A,5A,10/25/2024,Robert,Renzulli,Residential,BROOKLYN,11212,Not an Ejectment,Possession,40.661951,-73.908776,16.0,42.0,916.0,3397844.0,3.035890e+09,Brownsville
130239,310140/23,6969,507 EAST 161 STREET,13D,01/30/2024,David,Smith,Residential,BRONX,10451,Not an Ejectment,Possession,40.823066,-73.910004,3.0,17.0,141.0,2116648.0,2.023660e+09,Morrisania-Melrose
130240,61089/17,293496,75-25 153RD STREET,1104,09/21/2017,George,Essock,Residential,QUEENS,11367,Not an Ejectment,Possession,40.725735,-73.813781,8.0,24.0,77908.0,4531846.0,4.068090e+09,Kew Gardens Hills

In [34]:
df_shelter_people

,Date of Census,Total Adults in Shelter,Total Children in Shelter,Total Individuals in Shelter,Single Adult Men in Shelter,Single Adult Women in Shelter,Total Single Adults in Shelter,Families with Children in Shelter,Adults in Families with Children in Shelter,Children in Families with Children in Shelter,Total Individuals in Families with Children in Shelter,Adult Families in Shelter,Individuals in Adult Families in Shelter
0,03/01/2021,35195,16746,51941,13936,4543,18479,9593,12662,16746,29408,1920,4054
1,03/02/2021,35202,16746,51948,13962,4526,18488,9590,12658,16746,29404,1922,4056
2,03/03/2021,35108,16720,51828,13931,4503,18434,9579,12638,16720,29358,1913,4036
3,03/04/2021,35176,16720,51896,13989,4526,18515,9578,12626,16720,29346,1911,4035
4,03/05/2021,35103,16766,51869,13939,4485,18424,9598,12647,16766,29413,1908,4032
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1957,07/10/2026,54718,28339,83057,18199,7359,25558,16404,24148,28339,52487,2312,5012
1958,07/11/2026,54773,28363,83136,18219,7355,25574,16429,24170,28363,52533,2319,5029
1959,07/12/2026,54758,28289,83047,18262,7372,25634,16394,24107,28289,52396,2315,5017
1960,07/13/2026,54781,28289,83070,18309,7359,25668,16386,24096,28289,52385,2314,5017
1961,07/14/2026,54646,28203,82849,18258,7353,25611,16350,24032,28203,52235,2307,5003